### ISSUE TITLE
buffer以下のレコード数はINSERTされずに切り落とされる

### ISSUE THREAD

**Issue by itohdak** [ponyo877/dummy_data_generator#2]
configの設定で、recordcountをbufferで割り切れない値に設定した場合、
その端数分のレコードはINSERTされずにプログラムが終了してしまうような気がします。
特に、recordcount < bufferの値を設定した場合は、何もINSERTされません。

このあたりが原因かもです。
https://github.com/ponyo877/dummy_data_generator/blob/dc2576315b5a228a2914357576294651e388d98d/internal/model/table.go#L160-L163

P.S.
こちらのツール、たまたまググってたらZennの記事が見つかり、
その後便利に使わせていただいております！ありがとうございます！

**Comment by ponyo877** [comment]
以下のPRで修正しました.  
https://github.com/ponyo877/dummy_data_generator/pull/3

確認お願いします!

**Comment by itohdak** [comment]
@ponyo877 
問題なく治ってそうでした！ありがとうございます！
